#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                               0

// Legacy FRLG publications below are collision tombstones only. Runtime content must use
// the TRAINER_FRLG_* identities in the live all-regions block.
#define TRAINER_YOUNGSTER_BEN                      1
#define TRAINER_YOUNGSTER_CALVIN                   2
#define TRAINER_YOUNGSTER_JOSH                     3
#define TRAINER_YOUNGSTER_TIMMY                    4
#define TRAINER_YOUNGSTER_JOEY                     5
#define TRAINER_YOUNGSTER_DAN                      6
#define TRAINER_YOUNGSTER_CHAD                     7
#define TRAINER_YOUNGSTER_TYLER                    8
#define TRAINER_YOUNGSTER_EDDIE                    9
#define TRAINER_YOUNGSTER_DILLON                   10
#define TRAINER_YOUNGSTER_YASU                     11
#define TRAINER_YOUNGSTER_DAVE                     12
#define TRAINER_YOUNGSTER_BEN_2                    13
#define TRAINER_BUG_CATCHER_RICK                   14
#define TRAINER_BUG_CATCHER_DOUG                   15
#define TRAINER_BUG_CATCHER_SAMMY                  16
#define TRAINER_BUG_CATCHER_COLTON                 17
#define TRAINER_BUG_CATCHER_GREG                   18
#define TRAINER_BUG_CATCHER_JAMES                  19
#define TRAINER_BUG_CATCHER_KENT                   20
#define TRAINER_BUG_CATCHER_ROBBY                  21
#define TRAINER_BUG_CATCHER_CALE                   22
#define TRAINER_BUG_CATCHER_KEIGO                  23
#define TRAINER_BUG_CATCHER_ELIJAH                 24
#define TRAINER_BUG_CATCHER_BRENT                  25
#define TRAINER_BUG_CATCHER_CONNER                 26
#define TRAINER_LASS_JANICE                        27
#define TRAINER_LASS_SALLY                         28
#define TRAINER_LASS_ROBIN                         29
#define TRAINER_LASS_CRISSY                        30
#define TRAINER_LASS_MIRIAM                        31
#define TRAINER_LASS_IRIS                          32
#define TRAINER_LASS_RELI                          33
#define TRAINER_LASS_ALI                           34
#define TRAINER_LASS_HALEY                         35
#define TRAINER_LASS_ANN                           36
#define TRAINER_LASS_DAWN                          37
#define TRAINER_LASS_PAIGE                         38
#define TRAINER_LASS_ANDREA                        39
#define TRAINER_LASS_MEGAN                         40
#define TRAINER_LASS_JULIA                         41
#define TRAINER_LASS_KAY                           42
#define TRAINER_LASS_LISA                          43
#define TRAINER_SAILOR_EDMOND                      44
#define TRAINER_SAILOR_TREVOR                      45
#define TRAINER_SAILOR_LEONARD                     46
#define TRAINER_SAILOR_DUNCAN                      47
#define TRAINER_SAILOR_HUEY                        48
#define TRAINER_SAILOR_DYLAN                       49
#define TRAINER_SAILOR_PHILLIP                     50
#define TRAINER_SAILOR_DWAYNE                      51
#define TRAINER_CAMPER_LIAM                        52
#define TRAINER_CAMPER_SHANE                       53
#define TRAINER_CAMPER_ETHAN                       54
#define TRAINER_CAMPER_RICKY                       55
#define TRAINER_CAMPER_JEFF                        56
#define TRAINER_CAMPER_CHRIS                       57
#define TRAINER_CAMPER_DREW                        58
#define TRAINER_PICNICKER_DIANA                    59
#define TRAINER_PICNICKER_NANCY                    60
#define TRAINER_PICNICKER_ISABELLE                 61
#define TRAINER_PICNICKER_KELSEY                   62
#define TRAINER_PICNICKER_ALICIA                   63
#define TRAINER_PICNICKER_CAITLIN                  64
#define TRAINER_PICNICKER_HEIDI                    65
#define TRAINER_PICNICKER_CAROL                    66
#define TRAINER_PICNICKER_SOFIA                    67
#define TRAINER_PICNICKER_MARTHA                   68
#define TRAINER_PICNICKER_TINA                     69
#define TRAINER_PICNICKER_HANNAH                   70
#define TRAINER_POKEMANIAC_MARK                    71
#define TRAINER_POKEMANIAC_HERMAN                  72
#define TRAINER_POKEMANIAC_COOPER                  73
#define TRAINER_POKEMANIAC_STEVE                   74
#define TRAINER_POKEMANIAC_WINSTON                 75
#define TRAINER_POKEMANIAC_DAWSON                  76
#define TRAINER_POKEMANIAC_ASHTON                  77
#define TRAINER_SUPER_NERD_JOVAN                   78
#define TRAINER_SUPER_NERD_MIGUEL                  79
#define TRAINER_SUPER_NERD_AIDAN                   80
#define TRAINER_SUPER_NERD_GLENN                   81
#define TRAINER_SUPER_NERD_LESLIE                  82
#define TRAINER_SUPER_NERD_ERIK                    83
#define TRAINER_SUPER_NERD_AVERY                   84
#define TRAINER_SUPER_NERD_DEREK                   85
#define TRAINER_SUPER_NERD_ZAC                     86
#define TRAINER_HIKER_MARCOS                       87
#define TRAINER_HIKER_FRANKLIN                     88
#define TRAINER_HIKER_NOB                          89
#define TRAINER_HIKER_WAYNE                        90
#define TRAINER_HIKER_ALAN                         91
#define TRAINER_HIKER_BRICE                        92
#define TRAINER_HIKER_CLARK                        93
#define TRAINER_HIKER_TRENT                        94
#define TRAINER_HIKER_DUDLEY                       95
#define TRAINER_HIKER_ALLEN                        96
#define TRAINER_HIKER_ERIC                         97
#define TRAINER_HIKER_LENNY                        98
#define TRAINER_HIKER_OLIVER                       99
#define TRAINER_HIKER_LUCAS                        100
#define TRAINER_BIKER_JARED                        101
#define TRAINER_BIKER_MALIK                        102
#define TRAINER_BIKER_ERNEST                       103
#define TRAINER_BIKER_ALEX                         104
#define TRAINER_BIKER_LAO                          105
#define TRAINER_BIKER_HIDEO                        106
#define TRAINER_BIKER_RUBEN                        107
#define TRAINER_BIKER_BILLY                        108
#define TRAINER_BIKER_NIKOLAS                      109
#define TRAINER_BIKER_JAXON                        110
#define TRAINER_BIKER_WILLIAM                      111
#define TRAINER_BIKER_LUKAS                        112
#define TRAINER_BIKER_ISAAC                        113
#define TRAINER_BIKER_GERALD                       114
#define TRAINER_BURGLAR_QUINN                      115
#define TRAINER_BURGLAR_RAMON                      116
#define TRAINER_BURGLAR_DUSTY                      117
#define TRAINER_BURGLAR_ARNIE                      118
#define TRAINER_BURGLAR_SIMON                      119
#define TRAINER_BURGLAR_LEWIS                      120
#define TRAINER_ENGINEER_BAILY                     121
#define TRAINER_ENGINEER_BRAXTON                   122
#define TRAINER_ENGINEER_BERNIE                    123
#define TRAINER_FISHERMAN_DALE                     124
#define TRAINER_FISHERMAN_BARNY                    125
#define TRAINER_FISHERMAN_NED                      126
#define TRAINER_FISHERMAN_CHIP                     127
#define TRAINER_FISHERMAN_HANK                     128
#define TRAINER_FISHERMAN_ELLIOT                   129
#define TRAINER_FISHERMAN_RONALD                   130
#define TRAINER_FISHERMAN_CLAUDE                   131
#define TRAINER_FISHERMAN_WADE                     132
#define TRAINER_FISHERMAN_NOLAN                    133
#define TRAINER_FISHERMAN_ANDREW                   134
#define TRAINER_SWIMMER_MALE_LUIS                  135
#define TRAINER_SWIMMER_MALE_RICHARD               136
#define TRAINER_SWIMMER_MALE_REECE                 137
#define TRAINER_SWIMMER_MALE_MATTHEW               138
#define TRAINER_SWIMMER_MALE_DOUGLAS               139
#define TRAINER_SWIMMER_MALE_DAVID                 140
#define TRAINER_SWIMMER_MALE_TONY                  141
#define TRAINER_SWIMMER_MALE_AXLE                  142
#define TRAINER_SWIMMER_MALE_BARRY                 143
#define TRAINER_SWIMMER_MALE_DEAN                  144
#define TRAINER_SWIMMER_MALE_DARRIN                145
#define TRAINER_SWIMMER_MALE_SPENCER               146
#define TRAINER_SWIMMER_MALE_JACK                  147
#define TRAINER_SWIMMER_MALE_JEROME                148
#define TRAINER_SWIMMER_MALE_ROLAND                149
#define TRAINER_CUE_BALL_KOJI                      150
#define TRAINER_CUE_BALL_LUKE                      151
#define TRAINER_CUE_BALL_CAMRON                    152
#define TRAINER_CUE_BALL_RAUL                      153
#define TRAINER_CUE_BALL_ISAIAH                    154
#define TRAINER_CUE_BALL_ZEEK                      155
#define TRAINER_CUE_BALL_JAMAL                     156
#define TRAINER_CUE_BALL_COREY                     157
#define TRAINER_CUE_BALL_CHASE                     158
#define TRAINER_GAMER_HUGO                         159
#define TRAINER_GAMER_JASPER                       160
#define TRAINER_GAMER_DIRK                         161
#define TRAINER_GAMER_DARIAN                       162
#define TRAINER_GAMER_STAN                         163
#define TRAINER_GAMER_RICH                         164
#define TRAINER_BEAUTY_BRIDGET                     165
#define TRAINER_BEAUTY_TAMIA                       166
#define TRAINER_BEAUTY_LORI                        167
#define TRAINER_BEAUTY_LOLA                        168
#define TRAINER_BEAUTY_SHEILA                      169
#define TRAINER_SWIMMER_FEMALE_TIFFANY             170
#define TRAINER_SWIMMER_FEMALE_NORA                171
#define TRAINER_SWIMMER_FEMALE_MELISSA             172
#define TRAINER_BEAUTY_GRACE                       173
#define TRAINER_BEAUTY_OLIVIA                      174
#define TRAINER_BEAUTY_LAUREN                      175
#define TRAINER_SWIMMER_FEMALE_ANYA                176
#define TRAINER_SWIMMER_FEMALE_ALICE               177
#define TRAINER_SWIMMER_FEMALE_CONNIE              178
#define TRAINER_SWIMMER_FEMALE_SHIRLEY             179
#define TRAINER_PSYCHIC_JOHAN                      180
#define TRAINER_PSYCHIC_TYRON                      181
#define TRAINER_PSYCHIC_CAMERON                    182
#define TRAINER_PSYCHIC_PRESTON                    183
#define TRAINER_ROCKER_RANDALL                     184
#define TRAINER_ROCKER_LUCA                        185
#define TRAINER_JUGGLER_DALTON                     186
#define TRAINER_JUGGLER_NELSON                     187
#define TRAINER_JUGGLER_KIRK                       188
#define TRAINER_JUGGLER_SHAWN                      189
#define TRAINER_JUGGLER_GREGORY                    190
#define TRAINER_JUGGLER_EDWARD                     191
#define TRAINER_JUGGLER_KAYDEN                     192
#define TRAINER_JUGGLER_NATE                       193
#define TRAINER_TAMER_PHIL                         194
#define TRAINER_TAMER_EDGAR                        195
#define TRAINER_TAMER_JASON                        196
#define TRAINER_TAMER_COLE                         197
#define TRAINER_TAMER_VINCENT                      198
#define TRAINER_TAMER_JOHN                         199
#define TRAINER_BIRD_KEEPER_SEBASTIAN              200
#define TRAINER_BIRD_KEEPER_PERRY                  201
#define TRAINER_BIRD_KEEPER_ROBERT                 202
#define TRAINER_BIRD_KEEPER_DONALD                 203
#define TRAINER_BIRD_KEEPER_BENNY                  204
#define TRAINER_BIRD_KEEPER_EDWIN                  205
#define TRAINER_BIRD_KEEPER_CHESTER                206
#define TRAINER_BIRD_KEEPER_WILTON                 207
#define TRAINER_BIRD_KEEPER_RAMIRO                 208
#define TRAINER_BIRD_KEEPER_JACOB                  209
#define TRAINER_BIRD_KEEPER_ROGER                  210
#define TRAINER_BIRD_KEEPER_REED                   211
#define TRAINER_BIRD_KEEPER_KEITH                  212
#define TRAINER_BIRD_KEEPER_CARTER                 213
#define TRAINER_BIRD_KEEPER_MITCH                  214
#define TRAINER_BIRD_KEEPER_BECK                   215
#define TRAINER_BIRD_KEEPER_MARLON                 216
#define TRAINER_BLACK_BELT_KOICHI                  217
#define TRAINER_BLACK_BELT_MIKE                    218
#define TRAINER_BLACK_BELT_HIDEKI                  219
#define TRAINER_BLACK_BELT_AARON                   220
#define TRAINER_BLACK_BELT_HITOSHI                 221
#define TRAINER_BLACK_BELT_ATSUSHI                 222
#define TRAINER_BLACK_BELT_KIYO                    223
#define TRAINER_BLACK_BELT_TAKASHI                 224
#define TRAINER_BLACK_BELT_DAISUKE                 225
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE            226
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR           227
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER          228
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE       229
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR      230
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER     231
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE            232
#define TRAINER_RIVAL_CERULEAN_BULBASAUR           233
#define TRAINER_RIVAL_CERULEAN_CHARMANDER          234
#define TRAINER_SCIENTIST_TED                      235
#define TRAINER_SCIENTIST_CONNOR                   236
#define TRAINER_SCIENTIST_JERRY                    237
#define TRAINER_SCIENTIST_JOSE                     238
#define TRAINER_SCIENTIST_RODNEY                   239
#define TRAINER_SCIENTIST_BEAU                     240
#define TRAINER_SCIENTIST_TAYLOR                   241
#define TRAINER_SCIENTIST_JOSHUA                   242
#define TRAINER_SCIENTIST_PARKER                   243
#define TRAINER_SCIENTIST_ED                       244
#define TRAINER_SCIENTIST_TRAVIS                   245
#define TRAINER_SCIENTIST_BRAYDON                  246
#define TRAINER_SCIENTIST_IVAN                     247
#define TRAINER_BOSS_GIOVANNI                      248
#define TRAINER_BOSS_GIOVANNI_2                    249
#define TRAINER_LEADER_GIOVANNI                    250
#define TRAINER_TEAM_ROCKET_GRUNT                  251
#define TRAINER_TEAM_ROCKET_GRUNT_2                252
#define TRAINER_TEAM_ROCKET_GRUNT_3                253
#define TRAINER_TEAM_ROCKET_GRUNT_4                254
#define TRAINER_TEAM_ROCKET_GRUNT_5                255
#define TRAINER_TEAM_ROCKET_GRUNT_6                256
#define TRAINER_TEAM_ROCKET_GRUNT_7                257
#define TRAINER_TEAM_ROCKET_GRUNT_8                258
#define TRAINER_TEAM_ROCKET_GRUNT_9                259
#define TRAINER_TEAM_ROCKET_GRUNT_10               260
#define TRAINER_TEAM_ROCKET_GRUNT_11               261
#define TRAINER_TEAM_ROCKET_GRUNT_12               262
#define TRAINER_TEAM_ROCKET_GRUNT_13               263
#define TRAINER_TEAM_ROCKET_GRUNT_14               264
#define TRAINER_TEAM_ROCKET_GRUNT_15               265
#define TRAINER_TEAM_ROCKET_GRUNT_16               266
#define TRAINER_TEAM_ROCKET_GRUNT_17               267
#define TRAINER_TEAM_ROCKET_GRUNT_18               268
#define TRAINER_TEAM_ROCKET_GRUNT_19               269
#define TRAINER_TEAM_ROCKET_GRUNT_20               270
#define TRAINER_TEAM_ROCKET_GRUNT_21               271
#define TRAINER_TEAM_ROCKET_GRUNT_22               272
#define TRAINER_TEAM_ROCKET_GRUNT_23               273
#define TRAINER_TEAM_ROCKET_GRUNT_24               274
#define TRAINER_TEAM_ROCKET_GRUNT_25               275
#define TRAINER_TEAM_ROCKET_GRUNT_26               276
#define TRAINER_TEAM_ROCKET_GRUNT_27               277
#define TRAINER_TEAM_ROCKET_GRUNT_28               278
#define TRAINER_TEAM_ROCKET_GRUNT_29               279
#define TRAINER_TEAM_ROCKET_GRUNT_30               280
#define TRAINER_TEAM_ROCKET_GRUNT_31               281
#define TRAINER_TEAM_ROCKET_GRUNT_32               282
#define TRAINER_TEAM_ROCKET_GRUNT_33               283
#define TRAINER_TEAM_ROCKET_GRUNT_34               284
#define TRAINER_TEAM_ROCKET_GRUNT_35               285
#define TRAINER_TEAM_ROCKET_GRUNT_36               286
#define TRAINER_TEAM_ROCKET_GRUNT_37               287
#define TRAINER_TEAM_ROCKET_GRUNT_38               288
#define TRAINER_TEAM_ROCKET_GRUNT_39               289
#define TRAINER_TEAM_ROCKET_GRUNT_40               290
#define TRAINER_TEAM_ROCKET_GRUNT_41               291
#define TRAINER_COOLTRAINER_SAMUEL                 292
#define TRAINER_COOLTRAINER_GEORGE                 293
#define TRAINER_COOLTRAINER_COLBY                  294
#define TRAINER_COOLTRAINER_PAUL                   295
#define TRAINER_COOLTRAINER_ROLANDO                296
#define TRAINER_COOLTRAINER_GILBERT                297
#define TRAINER_COOLTRAINER_OWEN                   298
#define TRAINER_COOLTRAINER_BERKE                  299
#define TRAINER_COOLTRAINER_YUJI                   300
#define TRAINER_COOLTRAINER_WARREN                 301
#define TRAINER_COOLTRAINER_MARY                   302
#define TRAINER_COOLTRAINER_CAROLINE               303
#define TRAINER_COOLTRAINER_ALEXA                  304
#define TRAINER_COOLTRAINER_SHANNON                305
#define TRAINER_COOLTRAINER_NAOMI                  306
#define TRAINER_COOLTRAINER_BROOKE                 307
#define TRAINER_COOLTRAINER_AUSTINA                308
#define TRAINER_COOLTRAINER_JULIE                  309
#define TRAINER_ELITE_FOUR_LORELEI                 310
#define TRAINER_ELITE_FOUR_BRUNO                   311
#define TRAINER_ELITE_FOUR_AGATHA                  312
#define TRAINER_ELITE_FOUR_LANCE                   313
#define TRAINER_LEADER_BROCK                       314
#define TRAINER_LEADER_MISTY                       315
#define TRAINER_LEADER_LT_SURGE                    316
#define TRAINER_LEADER_ERIKA                       317
#define TRAINER_LEADER_KOGA                        318
#define TRAINER_LEADER_BLAINE                      319
#define TRAINER_LEADER_SABRINA                     320
#define TRAINER_GENTLEMAN_THOMAS                   321
#define TRAINER_GENTLEMAN_ARTHUR                   322
#define TRAINER_GENTLEMAN_TUCKER                   323
#define TRAINER_GENTLEMAN_NORTON                   324
#define TRAINER_GENTLEMAN_WALTER                   325
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE             326
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR            327
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER           328
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE       329
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR      330
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER     331
#define TRAINER_RIVAL_SILPH_SQUIRTLE               332
#define TRAINER_RIVAL_SILPH_BULBASAUR              333
#define TRAINER_RIVAL_SILPH_CHARMANDER             334
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE        335
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR       336
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER      337
#define TRAINER_CHAMPION_FIRST_SQUIRTLE            338
#define TRAINER_CHAMPION_FIRST_BULBASAUR           339
#define TRAINER_CHAMPION_FIRST_CHARMANDER          340
#define TRAINER_CHANNELER_PATRICIA                 341
#define TRAINER_CHANNELER_CARLY                    342
#define TRAINER_CHANNELER_HOPE                     343
#define TRAINER_CHANNELER_PAULA                    344
#define TRAINER_CHANNELER_LAUREL                   345
#define TRAINER_CHANNELER_JODY                     346
#define TRAINER_CHANNELER_TAMMY                    347
#define TRAINER_CHANNELER_RUTH                     348
#define TRAINER_CHANNELER_KARINA                   349
#define TRAINER_CHANNELER_JANAE                    350
#define TRAINER_CHANNELER_ANGELICA                 351
#define TRAINER_CHANNELER_EMILIA                   352
#define TRAINER_CHANNELER_JENNIFER                 353
#define TRAINER_CHANNELER_AMANDA                   354
#define TRAINER_CHANNELER_STACY                    355
#define TRAINER_CHANNELER_TASHA                    356
#define TRAINER_HIKER_JEREMY                       357
#define TRAINER_PICNICKER_ALMA                     358
#define TRAINER_PICNICKER_SUSIE                    359
#define TRAINER_PICNICKER_VALERIE                  360
#define TRAINER_PICNICKER_GWEN                     361
#define TRAINER_BIKER_VIRGIL                       362
#define TRAINER_CAMPER_FLINT                       363
#define TRAINER_PICNICKER_MISSY                    364
#define TRAINER_PICNICKER_IRENE                    365
#define TRAINER_PICNICKER_DANA                     366
#define TRAINER_PICNICKER_ARIANA                   367
#define TRAINER_PICNICKER_LEAH                     368
#define TRAINER_CAMPER_JUSTIN                      369
#define TRAINER_PICNICKER_YAZMIN                   370
#define TRAINER_PICNICKER_KINDRA                   371
#define TRAINER_PICNICKER_BECKY                    372
#define TRAINER_PICNICKER_CELIA                    373
#define TRAINER_GENTLEMAN_BROOKS                   374
#define TRAINER_GENTLEMAN_LAMAR                    375
#define TRAINER_TWINS_ELI_ANNE                     376
#define TRAINER_COOL_COUPLE_RAY_TYRA               377
#define TRAINER_YOUNG_COUPLE_GIA_JES               378
#define TRAINER_TWINS_KIRI_JAN                     379
#define TRAINER_CRUSH_KIN_RON_MYA                  380
#define TRAINER_YOUNG_COUPLE_LEA_JED               381
#define TRAINER_SIS_AND_BRO_LIA_LUC                382
#define TRAINER_SIS_AND_BRO_LIL_IAN                383
#define TRAINER_YOUNGSTER_BEN_3                    384
#define TRAINER_YOUNGSTER_BEN_4                    385
#define TRAINER_YOUNGSTER_CHAD_2                   386
#define TRAINER_LASS_RELI_2                        387
#define TRAINER_LASS_RELI_3                        388
#define TRAINER_YOUNGSTER_TIMMY_2                  389
#define TRAINER_YOUNGSTER_TIMMY_3                  390
#define TRAINER_YOUNGSTER_TIMMY_4                  391
#define TRAINER_YOUNGSTER_CHAD_3                   392
#define TRAINER_LASS_JANICE_2                      393
#define TRAINER_LASS_JANICE_3                      394
#define TRAINER_YOUNGSTER_CHAD_4                   395
#define TRAINER_HIKER_FRANKLIN_2                   396
#define TRAINER_PKMN_PROF_PROF_OAK                 397
#define TRAINER_TEAM_ROCKET_GRUNT_42               398
#define TRAINER_PSYCHIC_JACLYN                     399
#define TRAINER_CRUSH_GIRL_SHARON                  400
#define TRAINER_TUBER_AMIRA                        401
#define TRAINER_PKMN_BREEDER_ALIZE                 402
#define TRAINER_PKMN_RANGER_NICOLAS                403
#define TRAINER_PKMN_RANGER_MADELINE               404
#define TRAINER_AROMA_LADY_NIKKI                   405
#define TRAINER_RUIN_MANIAC_STANLY                 406
#define TRAINER_LADY_JACKI                         407
#define TRAINER_PAINTER_DAISY                      408
#define TRAINER_BIKER_GOON                         409
#define TRAINER_BIKER_GOON_2                       410
#define TRAINER_BIKER_GOON_3                       411
#define TRAINER_BUG_CATCHER_ANTHONY                412
#define TRAINER_BUG_CATCHER_CHARLIE                413
#define TRAINER_TWINS_ELI_ANNE_2                   414
#define TRAINER_YOUNGSTER_JOHNSON                  415
#define TRAINER_BIKER_RICARDO                      416
#define TRAINER_BIKER_JAREN                        417
#define TRAINER_TEAM_ROCKET_GRUNT_43               418
#define TRAINER_TEAM_ROCKET_GRUNT_44               419
#define TRAINER_TEAM_ROCKET_GRUNT_45               420
#define TRAINER_TEAM_ROCKET_GRUNT_46               421
#define TRAINER_TEAM_ROCKET_GRUNT_47               422
#define TRAINER_TEAM_ROCKET_GRUNT_48               423
#define TRAINER_TEAM_ROCKET_ADMIN                  424
#define TRAINER_TEAM_ROCKET_ADMIN_2                425
#define TRAINER_SCIENTIST_GIDEON                   426
#define TRAINER_SWIMMER_FEMALE_AMARA               427
#define TRAINER_SWIMMER_FEMALE_MARIA               428
#define TRAINER_SWIMMER_FEMALE_ABIGAIL             429
#define TRAINER_SWIMMER_MALE_FINN                  430
#define TRAINER_SWIMMER_MALE_GARRETT               431
#define TRAINER_FISHERMAN_TOMMY                    432
#define TRAINER_CRUSH_GIRL_TANYA                   433
#define TRAINER_BLACK_BELT_SHEA                    434
#define TRAINER_BLACK_BELT_HUGH                    435
#define TRAINER_CAMPER_BRYCE                       436
#define TRAINER_PICNICKER_CLAIRE                   437
#define TRAINER_CRUSH_KIN_MIK_KIA                  438
#define TRAINER_AROMA_LADY_VIOLET                  439
#define TRAINER_TUBER_ALEXIS                       440
#define TRAINER_TWINS_JOY_MEG                      441
#define TRAINER_SWIMMER_FEMALE_TISHA               442
#define TRAINER_PAINTER_CELINA                     443
#define TRAINER_PAINTER_RAYNA                      444
#define TRAINER_LADY_GILLIAN                       445
#define TRAINER_YOUNGSTER_DESTIN                   446
#define TRAINER_SWIMMER_MALE_TOBY                  447
#define TRAINER_TEAM_ROCKET_GRUNT_49               448
#define TRAINER_TEAM_ROCKET_GRUNT_50               449
#define TRAINER_TEAM_ROCKET_GRUNT_51               450
#define TRAINER_BIRD_KEEPER_MILO                   451
#define TRAINER_BIRD_KEEPER_CHAZ                   452
#define TRAINER_BIRD_KEEPER_HAROLD                 453
#define TRAINER_FISHERMAN_TYLOR                    454
#define TRAINER_SWIMMER_MALE_MYMO                  455
#define TRAINER_SWIMMER_FEMALE_NICOLE              456
#define TRAINER_SIS_AND_BRO_AVA_GEB                457
#define TRAINER_AROMA_LADY_ROSE                    458
#define TRAINER_SWIMMER_MALE_SAMIR                 459
#define TRAINER_SWIMMER_FEMALE_DENISE              460
#define TRAINER_TWINS_MIU_MIA                      461
#define TRAINER_HIKER_EARL                         462
#define TRAINER_RUIN_MANIAC_FOSTER                 463
#define TRAINER_RUIN_MANIAC_LARRY                  464
#define TRAINER_HIKER_DARYL                        465
#define TRAINER_POKEMANIAC_HECTOR                  466
#define TRAINER_PSYCHIC_DARIO                      467
#define TRAINER_PSYCHIC_RODETTE                    468
#define TRAINER_AROMA_LADY_MIAH                    469
#define TRAINER_YOUNG_COUPLE_EVE_JON               470
#define TRAINER_JUGGLER_MASON                      471
#define TRAINER_CRUSH_GIRL_CYNDY                   472
#define TRAINER_CRUSH_GIRL_JOCELYN                 473
#define TRAINER_TAMER_EVAN                         474
#define TRAINER_POKEMANIAC_MARK_2                  475
#define TRAINER_PKMN_RANGER_LOGAN                  476
#define TRAINER_PKMN_RANGER_JACKSON                477
#define TRAINER_PKMN_RANGER_BETH                   478
#define TRAINER_PKMN_RANGER_KATELYN                479
#define TRAINER_COOLTRAINER_LEROY                  480
#define TRAINER_COOLTRAINER_MICHELLE               481
#define TRAINER_COOL_COUPLE_LEX_NYA                482
#define TRAINER_RUIN_MANIAC_BRANDON                483
#define TRAINER_RUIN_MANIAC_BENJAMIN               484
#define TRAINER_PAINTER_EDNA                       485
#define TRAINER_GENTLEMAN_CLIFFORD                 486
#define TRAINER_LADY_SELPHY                        487
#define TRAINER_RUIN_MANIAC_LAWSON                 488
#define TRAINER_PSYCHIC_LAURA                      489
#define TRAINER_PKMN_BREEDER_BETHANY               490
#define TRAINER_PKMN_BREEDER_ALLISON               491
#define TRAINER_BUG_CATCHER_GARRET                 492
#define TRAINER_BUG_CATCHER_JONAH                  493
#define TRAINER_BUG_CATCHER_VANCE                  494
#define TRAINER_YOUNGSTER_NASH                     495
#define TRAINER_YOUNGSTER_CORDELL                  496
#define TRAINER_LASS_DALIA                         497
#define TRAINER_LASS_JOANA                         498
#define TRAINER_CAMPER_RILEY                       499
#define TRAINER_PICNICKER_MARCY                    500
#define TRAINER_RUIN_MANIAC_LAYTON                 501
#define TRAINER_PICNICKER_KELSEY_2                 502
#define TRAINER_PICNICKER_KELSEY_3                 503
#define TRAINER_PICNICKER_KELSEY_4                 504
#define TRAINER_CAMPER_RICKY_2                     505
#define TRAINER_CAMPER_RICKY_3                     506
#define TRAINER_CAMPER_RICKY_4                     507
#define TRAINER_CAMPER_JEFF_2                      508
#define TRAINER_CAMPER_JEFF_3                      509
#define TRAINER_CAMPER_JEFF_4                      510
#define TRAINER_PICNICKER_ISABELLE_2               511
#define TRAINER_PICNICKER_ISABELLE_3               512
#define TRAINER_PICNICKER_ISABELLE_4               513
#define TRAINER_YOUNGSTER_YASU_2                   514
#define TRAINER_YOUNGSTER_YASU_3                   515
#define TRAINER_ENGINEER_BERNIE_2                  516
#define TRAINER_GAMER_DARIAN_2                     517
#define TRAINER_CAMPER_CHRIS_2                     518
#define TRAINER_CAMPER_CHRIS_3                     519
#define TRAINER_CAMPER_CHRIS_4                     520
#define TRAINER_PICNICKER_ALICIA_2                 521
#define TRAINER_PICNICKER_ALICIA_3                 522
#define TRAINER_PICNICKER_ALICIA_4                 523
#define TRAINER_HIKER_JEREMY_2                     524
#define TRAINER_POKEMANIAC_MARK_3                  525
#define TRAINER_POKEMANIAC_HERMAN_2                526
#define TRAINER_POKEMANIAC_HERMAN_3                527
#define TRAINER_HIKER_TRENT_2                      528
#define TRAINER_LASS_MEGAN_2                       529
#define TRAINER_LASS_MEGAN_3                       530
#define TRAINER_SUPER_NERD_GLENN_2                 531
#define TRAINER_GAMER_RICH_2                       532
#define TRAINER_BIKER_JAREN_2                      533
#define TRAINER_FISHERMAN_ELLIOT_2                 534
#define TRAINER_ROCKER_LUCA_2                      535
#define TRAINER_BEAUTY_SHEILA_2                    536
#define TRAINER_BIRD_KEEPER_ROBERT_2               537
#define TRAINER_BIRD_KEEPER_ROBERT_3               538
#define TRAINER_PICNICKER_SUSIE_2                  539
#define TRAINER_PICNICKER_SUSIE_3                  540
#define TRAINER_PICNICKER_SUSIE_4                  541
#define TRAINER_BIKER_LUKAS_2                      542
#define TRAINER_BIRD_KEEPER_BENNY_2                543
#define TRAINER_BIRD_KEEPER_BENNY_3                544
#define TRAINER_BIRD_KEEPER_MARLON_2               545
#define TRAINER_BIRD_KEEPER_MARLON_3               546
#define TRAINER_BEAUTY_GRACE_2                     547
#define TRAINER_BIRD_KEEPER_CHESTER_2              548
#define TRAINER_BIRD_KEEPER_CHESTER_3              549
#define TRAINER_PICNICKER_BECKY_2                  550
#define TRAINER_PICNICKER_BECKY_3                  551
#define TRAINER_PICNICKER_BECKY_4                  552
#define TRAINER_CRUSH_KIN_RON_MYA_2                553
#define TRAINER_CRUSH_KIN_RON_MYA_3                554
#define TRAINER_CRUSH_KIN_RON_MYA_4                555
#define TRAINER_BIKER_RUBEN_2                      556
#define TRAINER_CUE_BALL_CAMRON_2                  557
#define TRAINER_BIKER_JAXON_2                      558
#define TRAINER_CUE_BALL_ISAIAH_2                  559
#define TRAINER_CUE_BALL_COREY_2                   560
#define TRAINER_BIRD_KEEPER_JACOB_2                561
#define TRAINER_BIRD_KEEPER_JACOB_3                562
#define TRAINER_SWIMMER_FEMALE_ALICE_2             563
#define TRAINER_SWIMMER_MALE_DARRIN_2              564
#define TRAINER_PICNICKER_MISSY_2                  565
#define TRAINER_PICNICKER_MISSY_3                  566
#define TRAINER_FISHERMAN_WADE_2                   567
#define TRAINER_SWIMMER_MALE_JACK_2                568
#define TRAINER_SIS_AND_BRO_LIL_IAN_2              569
#define TRAINER_SIS_AND_BRO_LIL_IAN_3              570
#define TRAINER_SWIMMER_MALE_FINN_2                571
#define TRAINER_CRUSH_GIRL_SHARON_2                572
#define TRAINER_CRUSH_GIRL_SHARON_3                573
#define TRAINER_CRUSH_GIRL_TANYA_2                 574
#define TRAINER_CRUSH_GIRL_TANYA_3                 575
#define TRAINER_BLACK_BELT_SHEA_2                  576
#define TRAINER_BLACK_BELT_SHEA_3                  577
#define TRAINER_BLACK_BELT_HUGH_2                  578
#define TRAINER_BLACK_BELT_HUGH_3                  579
#define TRAINER_CRUSH_KIN_MIK_KIA_2                580
#define TRAINER_CRUSH_KIN_MIK_KIA_3                581
#define TRAINER_TUBER_AMIRA_2                      582
#define TRAINER_TWINS_JOY_MEG_2                    583
#define TRAINER_PAINTER_RAYNA_2                    584
#define TRAINER_YOUNGSTER_DESTIN_2                 585
#define TRAINER_PKMN_BREEDER_ALIZE_2               586
#define TRAINER_YOUNG_COUPLE_GIA_JES_2             587
#define TRAINER_YOUNG_COUPLE_GIA_JES_3             588
#define TRAINER_BIRD_KEEPER_MILO_2                 589
#define TRAINER_BIRD_KEEPER_CHAZ_2                 590
#define TRAINER_BIRD_KEEPER_HAROLD_2               591
#define TRAINER_SWIMMER_FEMALE_NICOLE_2            592
#define TRAINER_PSYCHIC_JACLYN_2                   593
#define TRAINER_SWIMMER_MALE_SAMIR_2               594
#define TRAINER_HIKER_EARL_2                       595
#define TRAINER_RUIN_MANIAC_LARRY_2                596
#define TRAINER_POKEMANIAC_HECTOR_2                597
#define TRAINER_PSYCHIC_DARIO_2                    598
#define TRAINER_PSYCHIC_RODETTE_2                  599
#define TRAINER_JUGGLER_MASON_2                    600
#define TRAINER_PKMN_RANGER_NICOLAS_2              601
#define TRAINER_PKMN_RANGER_MADELINE_2             602
#define TRAINER_CRUSH_GIRL_CYNDY_2                 603
#define TRAINER_TAMER_EVAN_2                       604
#define TRAINER_PKMN_RANGER_JACKSON_2              605
#define TRAINER_PKMN_RANGER_KATELYN_2              606
#define TRAINER_COOLTRAINER_LEROY_2                607
#define TRAINER_COOLTRAINER_MICHELLE_2             608
#define TRAINER_COOL_COUPLE_LEX_NYA_2              609
#define TRAINER_BUG_CATCHER_COLTON_2               610
#define TRAINER_BUG_CATCHER_COLTON_3               611
#define TRAINER_BUG_CATCHER_COLTON_4               612
#define TRAINER_SWIMMER_MALE_MATTHEW_2             613
#define TRAINER_SWIMMER_MALE_TONY_2                614
#define TRAINER_SWIMMER_FEMALE_MELISSA_2           615
#define TRAINER_ELITE_FOUR_LORELEI_2               616
#define TRAINER_ELITE_FOUR_BRUNO_2                 617
#define TRAINER_ELITE_FOUR_AGATHA_2                618
#define TRAINER_ELITE_FOUR_LANCE_2                 619
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE          620
#define TRAINER_CHAMPION_REMATCH_BULBASAUR         621
#define TRAINER_CHAMPION_REMATCH_CHARMANDER        622
#define TRAINER_CUE_BALL_PAXTON                    623

// Live all-regions identities. Values are the literal legacy FRLG IDs rebased by 857.
#define TRAINER_FRLG_YOUNGSTER_BEN                         858
#define TRAINER_FRLG_YOUNGSTER_CALVIN                      859
#define TRAINER_FRLG_YOUNGSTER_JOSH                        860
#define TRAINER_FRLG_YOUNGSTER_TIMMY                       861
#define TRAINER_FRLG_YOUNGSTER_JOEY                        862
#define TRAINER_FRLG_YOUNGSTER_DAN                         863
#define TRAINER_FRLG_YOUNGSTER_CHAD                        864
#define TRAINER_FRLG_YOUNGSTER_TYLER                       865
#define TRAINER_FRLG_YOUNGSTER_EDDIE                       866
#define TRAINER_FRLG_YOUNGSTER_DILLON                      867
#define TRAINER_FRLG_YOUNGSTER_YASU                        868
#define TRAINER_FRLG_YOUNGSTER_DAVE                        869
#define TRAINER_FRLG_YOUNGSTER_BEN_2                       870
#define TRAINER_FRLG_BUG_CATCHER_RICK                      871
#define TRAINER_FRLG_BUG_CATCHER_DOUG                      872
#define TRAINER_FRLG_BUG_CATCHER_SAMMY                     873
#define TRAINER_FRLG_BUG_CATCHER_COLTON                    874
#define TRAINER_FRLG_BUG_CATCHER_GREG                      875
#define TRAINER_FRLG_BUG_CATCHER_JAMES                     876
#define TRAINER_FRLG_BUG_CATCHER_KENT                      877
#define TRAINER_FRLG_BUG_CATCHER_ROBBY                     878
#define TRAINER_FRLG_BUG_CATCHER_CALE                      879
#define TRAINER_FRLG_BUG_CATCHER_KEIGO                     880
#define TRAINER_FRLG_BUG_CATCHER_ELIJAH                    881
#define TRAINER_FRLG_BUG_CATCHER_BRENT                     882
#define TRAINER_FRLG_BUG_CATCHER_CONNER                    883
#define TRAINER_FRLG_LASS_JANICE                           884
#define TRAINER_FRLG_LASS_SALLY                            885
#define TRAINER_FRLG_LASS_ROBIN                            886
#define TRAINER_FRLG_LASS_CRISSY                           887
#define TRAINER_FRLG_LASS_MIRIAM                           888
#define TRAINER_FRLG_LASS_IRIS                             889
#define TRAINER_FRLG_LASS_RELI                             890
#define TRAINER_FRLG_LASS_ALI                              891
#define TRAINER_FRLG_LASS_HALEY                            892
#define TRAINER_FRLG_LASS_ANN                              893
#define TRAINER_FRLG_LASS_DAWN                             894
#define TRAINER_FRLG_LASS_PAIGE                            895
#define TRAINER_FRLG_LASS_ANDREA                           896
#define TRAINER_FRLG_LASS_MEGAN                            897
#define TRAINER_FRLG_LASS_JULIA                            898
#define TRAINER_FRLG_LASS_KAY                              899
#define TRAINER_FRLG_LASS_LISA                             900
#define TRAINER_FRLG_SAILOR_EDMOND                         901
#define TRAINER_FRLG_SAILOR_TREVOR                         902
#define TRAINER_FRLG_SAILOR_LEONARD                        903
#define TRAINER_FRLG_SAILOR_DUNCAN                         904
#define TRAINER_FRLG_SAILOR_HUEY                           905
#define TRAINER_FRLG_SAILOR_DYLAN                          906
#define TRAINER_FRLG_SAILOR_PHILLIP                        907
#define TRAINER_FRLG_SAILOR_DWAYNE                         908
#define TRAINER_FRLG_CAMPER_LIAM                           909
#define TRAINER_FRLG_CAMPER_SHANE                          910
#define TRAINER_FRLG_CAMPER_ETHAN                          911
#define TRAINER_FRLG_CAMPER_RICKY                          912
#define TRAINER_FRLG_CAMPER_JEFF                           913
#define TRAINER_FRLG_CAMPER_CHRIS                          914
#define TRAINER_FRLG_CAMPER_DREW                           915
#define TRAINER_FRLG_PICNICKER_DIANA                       916
#define TRAINER_FRLG_PICNICKER_NANCY                       917
#define TRAINER_FRLG_PICNICKER_ISABELLE                    918
#define TRAINER_FRLG_PICNICKER_KELSEY                      919
#define TRAINER_FRLG_PICNICKER_ALICIA                      920
#define TRAINER_FRLG_PICNICKER_CAITLIN                     921
#define TRAINER_FRLG_PICNICKER_HEIDI                       922
#define TRAINER_FRLG_PICNICKER_CAROL                       923
#define TRAINER_FRLG_PICNICKER_SOFIA                       924
#define TRAINER_FRLG_PICNICKER_MARTHA                      925
#define TRAINER_FRLG_PICNICKER_TINA                        926
#define TRAINER_FRLG_PICNICKER_HANNAH                      927
#define TRAINER_FRLG_POKEMANIAC_MARK                       928
#define TRAINER_FRLG_POKEMANIAC_HERMAN                     929
#define TRAINER_FRLG_POKEMANIAC_COOPER                     930
#define TRAINER_FRLG_POKEMANIAC_STEVE                      931
#define TRAINER_FRLG_POKEMANIAC_WINSTON                    932
#define TRAINER_FRLG_POKEMANIAC_DAWSON                     933
#define TRAINER_FRLG_POKEMANIAC_ASHTON                     934
#define TRAINER_FRLG_SUPER_NERD_JOVAN                      935
#define TRAINER_FRLG_SUPER_NERD_MIGUEL                     936
#define TRAINER_FRLG_SUPER_NERD_AIDAN                      937
#define TRAINER_FRLG_SUPER_NERD_GLENN                      938
#define TRAINER_FRLG_SUPER_NERD_LESLIE                     939
#define TRAINER_FRLG_SUPER_NERD_ERIK                       940
#define TRAINER_FRLG_SUPER_NERD_AVERY                      941
#define TRAINER_FRLG_SUPER_NERD_DEREK                      942
#define TRAINER_FRLG_SUPER_NERD_ZAC                        943
#define TRAINER_FRLG_HIKER_MARCOS                          944
#define TRAINER_FRLG_HIKER_FRANKLIN                        945
#define TRAINER_FRLG_HIKER_NOB                             946
#define TRAINER_FRLG_HIKER_WAYNE                           947
#define TRAINER_FRLG_HIKER_ALAN                            948
#define TRAINER_FRLG_HIKER_BRICE                           949
#define TRAINER_FRLG_HIKER_CLARK                           950
#define TRAINER_FRLG_HIKER_TRENT                           951
#define TRAINER_FRLG_HIKER_DUDLEY                          952
#define TRAINER_FRLG_HIKER_ALLEN                           953
#define TRAINER_FRLG_HIKER_ERIC                            954
#define TRAINER_FRLG_HIKER_LENNY                           955
#define TRAINER_FRLG_HIKER_OLIVER                          956
#define TRAINER_FRLG_HIKER_LUCAS                           957
#define TRAINER_FRLG_BIKER_JARED                           958
#define TRAINER_FRLG_BIKER_MALIK                           959
#define TRAINER_FRLG_BIKER_ERNEST                          960
#define TRAINER_FRLG_BIKER_ALEX                            961
#define TRAINER_FRLG_BIKER_LAO                             962
#define TRAINER_FRLG_BIKER_HIDEO                           963
#define TRAINER_FRLG_BIKER_RUBEN                           964
#define TRAINER_FRLG_BIKER_BILLY                           965
#define TRAINER_FRLG_BIKER_NIKOLAS                         966
#define TRAINER_FRLG_BIKER_JAXON                           967
#define TRAINER_FRLG_BIKER_WILLIAM                         968
#define TRAINER_FRLG_BIKER_LUKAS                           969
#define TRAINER_FRLG_BIKER_ISAAC                           970
#define TRAINER_FRLG_BIKER_GERALD                          971
#define TRAINER_FRLG_BURGLAR_QUINN                         972
#define TRAINER_FRLG_BURGLAR_RAMON                         973
#define TRAINER_FRLG_BURGLAR_DUSTY                         974
#define TRAINER_FRLG_BURGLAR_ARNIE                         975
#define TRAINER_FRLG_BURGLAR_SIMON                         976
#define TRAINER_FRLG_BURGLAR_LEWIS                         977
#define TRAINER_FRLG_ENGINEER_BAILY                        978
#define TRAINER_FRLG_ENGINEER_BRAXTON                      979
#define TRAINER_FRLG_ENGINEER_BERNIE                       980
#define TRAINER_FRLG_FISHERMAN_DALE                        981
#define TRAINER_FRLG_FISHERMAN_BARNY                       982
#define TRAINER_FRLG_FISHERMAN_NED                         983
#define TRAINER_FRLG_FISHERMAN_CHIP                        984
#define TRAINER_FRLG_FISHERMAN_HANK                        985
#define TRAINER_FRLG_FISHERMAN_ELLIOT                      986
#define TRAINER_FRLG_FISHERMAN_RONALD                      987
#define TRAINER_FRLG_FISHERMAN_CLAUDE                      988
#define TRAINER_FRLG_FISHERMAN_WADE                        989
#define TRAINER_FRLG_FISHERMAN_NOLAN                       990
#define TRAINER_FRLG_FISHERMAN_ANDREW                      991
#define TRAINER_FRLG_SWIMMER_MALE_LUIS                     992
#define TRAINER_FRLG_SWIMMER_MALE_RICHARD                  993
#define TRAINER_FRLG_SWIMMER_MALE_REECE                    994
#define TRAINER_FRLG_SWIMMER_MALE_MATTHEW                  995
#define TRAINER_FRLG_SWIMMER_MALE_DOUGLAS                  996
#define TRAINER_FRLG_SWIMMER_MALE_DAVID                    997
#define TRAINER_FRLG_SWIMMER_MALE_TONY                     998
#define TRAINER_FRLG_SWIMMER_MALE_AXLE                     999
#define TRAINER_FRLG_SWIMMER_MALE_BARRY                    1000
#define TRAINER_FRLG_SWIMMER_MALE_DEAN                     1001
#define TRAINER_FRLG_SWIMMER_MALE_DARRIN                   1002
#define TRAINER_FRLG_SWIMMER_MALE_SPENCER                  1003
#define TRAINER_FRLG_SWIMMER_MALE_JACK                     1004
#define TRAINER_FRLG_SWIMMER_MALE_JEROME                   1005
#define TRAINER_FRLG_SWIMMER_MALE_ROLAND                   1006
#define TRAINER_FRLG_CUE_BALL_KOJI                         1007
#define TRAINER_FRLG_CUE_BALL_LUKE                         1008
#define TRAINER_FRLG_CUE_BALL_CAMRON                       1009
#define TRAINER_FRLG_CUE_BALL_RAUL                         1010
#define TRAINER_FRLG_CUE_BALL_ISAIAH                       1011
#define TRAINER_FRLG_CUE_BALL_ZEEK                         1012
#define TRAINER_FRLG_CUE_BALL_JAMAL                        1013
#define TRAINER_FRLG_CUE_BALL_COREY                        1014
#define TRAINER_FRLG_CUE_BALL_CHASE                        1015
#define TRAINER_FRLG_GAMER_HUGO                            1016
#define TRAINER_FRLG_GAMER_JASPER                          1017
#define TRAINER_FRLG_GAMER_DIRK                            1018
#define TRAINER_FRLG_GAMER_DARIAN                          1019
#define TRAINER_FRLG_GAMER_STAN                            1020
#define TRAINER_FRLG_GAMER_RICH                            1021
#define TRAINER_FRLG_BEAUTY_BRIDGET                        1022
#define TRAINER_FRLG_BEAUTY_TAMIA                          1023
#define TRAINER_FRLG_BEAUTY_LORI                           1024
#define TRAINER_FRLG_BEAUTY_LOLA                           1025
#define TRAINER_FRLG_BEAUTY_SHEILA                         1026
#define TRAINER_FRLG_SWIMMER_FEMALE_TIFFANY                1027
#define TRAINER_FRLG_SWIMMER_FEMALE_NORA                   1028
#define TRAINER_FRLG_SWIMMER_FEMALE_MELISSA                1029
#define TRAINER_FRLG_BEAUTY_GRACE                          1030
#define TRAINER_FRLG_BEAUTY_OLIVIA                         1031
#define TRAINER_FRLG_BEAUTY_LAUREN                         1032
#define TRAINER_FRLG_SWIMMER_FEMALE_ANYA                   1033
#define TRAINER_FRLG_SWIMMER_FEMALE_ALICE                  1034
#define TRAINER_FRLG_SWIMMER_FEMALE_CONNIE                 1035
#define TRAINER_FRLG_SWIMMER_FEMALE_SHIRLEY                1036
#define TRAINER_FRLG_PSYCHIC_JOHAN                         1037
#define TRAINER_FRLG_PSYCHIC_TYRON                         1038
#define TRAINER_FRLG_PSYCHIC_CAMERON                       1039
#define TRAINER_FRLG_PSYCHIC_PRESTON                       1040
#define TRAINER_FRLG_ROCKER_RANDALL                        1041
#define TRAINER_FRLG_ROCKER_LUCA                           1042
#define TRAINER_FRLG_JUGGLER_DALTON                        1043
#define TRAINER_FRLG_JUGGLER_NELSON                        1044
#define TRAINER_FRLG_JUGGLER_KIRK                          1045
#define TRAINER_FRLG_JUGGLER_SHAWN                         1046
#define TRAINER_FRLG_JUGGLER_GREGORY                       1047
#define TRAINER_FRLG_JUGGLER_EDWARD                        1048
#define TRAINER_FRLG_JUGGLER_KAYDEN                        1049
#define TRAINER_FRLG_JUGGLER_NATE                          1050
#define TRAINER_FRLG_TAMER_PHIL                            1051
#define TRAINER_FRLG_TAMER_EDGAR                           1052
#define TRAINER_FRLG_TAMER_JASON                           1053
#define TRAINER_FRLG_TAMER_COLE                            1054
#define TRAINER_FRLG_TAMER_VINCENT                         1055
#define TRAINER_FRLG_TAMER_JOHN                            1056
#define TRAINER_FRLG_BIRD_KEEPER_SEBASTIAN                 1057
#define TRAINER_FRLG_BIRD_KEEPER_PERRY                     1058
#define TRAINER_FRLG_BIRD_KEEPER_ROBERT                    1059
#define TRAINER_FRLG_BIRD_KEEPER_DONALD                    1060
#define TRAINER_FRLG_BIRD_KEEPER_BENNY                     1061
#define TRAINER_FRLG_BIRD_KEEPER_EDWIN                     1062
#define TRAINER_FRLG_BIRD_KEEPER_CHESTER                   1063
#define TRAINER_FRLG_BIRD_KEEPER_WILTON                    1064
#define TRAINER_FRLG_BIRD_KEEPER_RAMIRO                    1065
#define TRAINER_FRLG_BIRD_KEEPER_JACOB                     1066
#define TRAINER_FRLG_BIRD_KEEPER_ROGER                     1067
#define TRAINER_FRLG_BIRD_KEEPER_REED                      1068
#define TRAINER_FRLG_BIRD_KEEPER_KEITH                     1069
#define TRAINER_FRLG_BIRD_KEEPER_CARTER                    1070
#define TRAINER_FRLG_BIRD_KEEPER_MITCH                     1071
#define TRAINER_FRLG_BIRD_KEEPER_BECK                      1072
#define TRAINER_FRLG_BIRD_KEEPER_MARLON                    1073
#define TRAINER_FRLG_BLACK_BELT_KOICHI                     1074
#define TRAINER_FRLG_BLACK_BELT_MIKE                       1075
#define TRAINER_FRLG_BLACK_BELT_HIDEKI                     1076
#define TRAINER_FRLG_BLACK_BELT_AARON                      1077
#define TRAINER_FRLG_BLACK_BELT_HITOSHI                    1078
#define TRAINER_FRLG_BLACK_BELT_ATSUSHI                    1079
#define TRAINER_FRLG_BLACK_BELT_KIYO                       1080
#define TRAINER_FRLG_BLACK_BELT_TAKASHI                    1081
#define TRAINER_FRLG_BLACK_BELT_DAISUKE                    1082
#define TRAINER_FRLG_RIVAL_OAKS_LAB_SQUIRTLE               1083
#define TRAINER_FRLG_RIVAL_OAKS_LAB_BULBASAUR              1084
#define TRAINER_FRLG_RIVAL_OAKS_LAB_CHARMANDER             1085
#define TRAINER_FRLG_RIVAL_ROUTE22_EARLY_SQUIRTLE          1086
#define TRAINER_FRLG_RIVAL_ROUTE22_EARLY_BULBASAUR         1087
#define TRAINER_FRLG_RIVAL_ROUTE22_EARLY_CHARMANDER        1088
#define TRAINER_FRLG_RIVAL_CERULEAN_SQUIRTLE               1089
#define TRAINER_FRLG_RIVAL_CERULEAN_BULBASAUR              1090
#define TRAINER_FRLG_RIVAL_CERULEAN_CHARMANDER             1091
#define TRAINER_FRLG_SCIENTIST_TED                         1092
#define TRAINER_FRLG_SCIENTIST_CONNOR                      1093
#define TRAINER_FRLG_SCIENTIST_JERRY                       1094
#define TRAINER_FRLG_SCIENTIST_JOSE                        1095
#define TRAINER_FRLG_SCIENTIST_RODNEY                      1096
#define TRAINER_FRLG_SCIENTIST_BEAU                        1097
#define TRAINER_FRLG_SCIENTIST_TAYLOR                      1098
#define TRAINER_FRLG_SCIENTIST_JOSHUA                      1099
#define TRAINER_FRLG_SCIENTIST_PARKER                      1100
#define TRAINER_FRLG_SCIENTIST_ED                          1101
#define TRAINER_FRLG_SCIENTIST_TRAVIS                      1102
#define TRAINER_FRLG_SCIENTIST_BRAYDON                     1103
#define TRAINER_FRLG_SCIENTIST_IVAN                        1104
#define TRAINER_FRLG_BOSS_GIOVANNI                         1105
#define TRAINER_FRLG_BOSS_GIOVANNI_2                       1106
#define TRAINER_FRLG_LEADER_GIOVANNI                       1107
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT                     1108
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_2                   1109
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_3                   1110
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_4                   1111
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_5                   1112
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_6                   1113
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_7                   1114
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_8                   1115
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_9                   1116
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_10                  1117
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_11                  1118
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_12                  1119
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_13                  1120
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_14                  1121
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_15                  1122
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_16                  1123
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_17                  1124
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_18                  1125
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_19                  1126
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_20                  1127
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_21                  1128
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_22                  1129
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_23                  1130
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_24                  1131
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_25                  1132
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_26                  1133
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_27                  1134
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_28                  1135
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_29                  1136
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_30                  1137
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_31                  1138
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_32                  1139
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_33                  1140
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_34                  1141
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_35                  1142
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_36                  1143
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_37                  1144
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_38                  1145
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_39                  1146
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_40                  1147
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_41                  1148
#define TRAINER_FRLG_COOLTRAINER_SAMUEL                    1149
#define TRAINER_FRLG_COOLTRAINER_GEORGE                    1150
#define TRAINER_FRLG_COOLTRAINER_COLBY                     1151
#define TRAINER_FRLG_COOLTRAINER_PAUL                      1152
#define TRAINER_FRLG_COOLTRAINER_ROLANDO                   1153
#define TRAINER_FRLG_COOLTRAINER_GILBERT                   1154
#define TRAINER_FRLG_COOLTRAINER_OWEN                      1155
#define TRAINER_FRLG_COOLTRAINER_BERKE                     1156
#define TRAINER_FRLG_COOLTRAINER_YUJI                      1157
#define TRAINER_FRLG_COOLTRAINER_WARREN                    1158
#define TRAINER_FRLG_COOLTRAINER_MARY                      1159
#define TRAINER_FRLG_COOLTRAINER_CAROLINE                  1160
#define TRAINER_FRLG_COOLTRAINER_ALEXA                     1161
#define TRAINER_FRLG_COOLTRAINER_SHANNON                   1162
#define TRAINER_FRLG_COOLTRAINER_NAOMI                     1163
#define TRAINER_FRLG_COOLTRAINER_BROOKE                    1164
#define TRAINER_FRLG_COOLTRAINER_AUSTINA                   1165
#define TRAINER_FRLG_COOLTRAINER_JULIE                     1166
#define TRAINER_FRLG_ELITE_FOUR_LORELEI                    1167
#define TRAINER_FRLG_ELITE_FOUR_BRUNO                      1168
#define TRAINER_FRLG_ELITE_FOUR_AGATHA                     1169
#define TRAINER_FRLG_ELITE_FOUR_LANCE                      1170
#define TRAINER_FRLG_LEADER_BROCK                          1171
#define TRAINER_FRLG_LEADER_MISTY                          1172
#define TRAINER_FRLG_LEADER_LT_SURGE                       1173
#define TRAINER_FRLG_LEADER_ERIKA                          1174
#define TRAINER_FRLG_LEADER_KOGA                           1175
#define TRAINER_FRLG_LEADER_BLAINE                         1176
#define TRAINER_FRLG_LEADER_SABRINA                        1177
#define TRAINER_FRLG_GENTLEMAN_THOMAS                      1178
#define TRAINER_FRLG_GENTLEMAN_ARTHUR                      1179
#define TRAINER_FRLG_GENTLEMAN_TUCKER                      1180
#define TRAINER_FRLG_GENTLEMAN_NORTON                      1181
#define TRAINER_FRLG_GENTLEMAN_WALTER                      1182
#define TRAINER_FRLG_RIVAL_SS_ANNE_SQUIRTLE                1183
#define TRAINER_FRLG_RIVAL_SS_ANNE_BULBASAUR               1184
#define TRAINER_FRLG_RIVAL_SS_ANNE_CHARMANDER              1185
#define TRAINER_FRLG_RIVAL_POKEMON_TOWER_SQUIRTLE          1186
#define TRAINER_FRLG_RIVAL_POKEMON_TOWER_BULBASAUR         1187
#define TRAINER_FRLG_RIVAL_POKEMON_TOWER_CHARMANDER        1188
#define TRAINER_FRLG_RIVAL_SILPH_SQUIRTLE                  1189
#define TRAINER_FRLG_RIVAL_SILPH_BULBASAUR                 1190
#define TRAINER_FRLG_RIVAL_SILPH_CHARMANDER                1191
#define TRAINER_FRLG_RIVAL_ROUTE22_LATE_SQUIRTLE           1192
#define TRAINER_FRLG_RIVAL_ROUTE22_LATE_BULBASAUR          1193
#define TRAINER_FRLG_RIVAL_ROUTE22_LATE_CHARMANDER         1194
#define TRAINER_FRLG_CHAMPION_FIRST_SQUIRTLE               1195
#define TRAINER_FRLG_CHAMPION_FIRST_BULBASAUR              1196
#define TRAINER_FRLG_CHAMPION_FIRST_CHARMANDER             1197
#define TRAINER_FRLG_CHANNELER_PATRICIA                    1198
#define TRAINER_FRLG_CHANNELER_CARLY                       1199
#define TRAINER_FRLG_CHANNELER_HOPE                        1200
#define TRAINER_FRLG_CHANNELER_PAULA                       1201
#define TRAINER_FRLG_CHANNELER_LAUREL                      1202
#define TRAINER_FRLG_CHANNELER_JODY                        1203
#define TRAINER_FRLG_CHANNELER_TAMMY                       1204
#define TRAINER_FRLG_CHANNELER_RUTH                        1205
#define TRAINER_FRLG_CHANNELER_KARINA                      1206
#define TRAINER_FRLG_CHANNELER_JANAE                       1207
#define TRAINER_FRLG_CHANNELER_ANGELICA                    1208
#define TRAINER_FRLG_CHANNELER_EMILIA                      1209
#define TRAINER_FRLG_CHANNELER_JENNIFER                    1210
#define TRAINER_FRLG_CHANNELER_AMANDA                      1211
#define TRAINER_FRLG_CHANNELER_STACY                       1212
#define TRAINER_FRLG_CHANNELER_TASHA                       1213
#define TRAINER_FRLG_HIKER_JEREMY                          1214
#define TRAINER_FRLG_PICNICKER_ALMA                        1215
#define TRAINER_FRLG_PICNICKER_SUSIE                       1216
#define TRAINER_FRLG_PICNICKER_VALERIE                     1217
#define TRAINER_FRLG_PICNICKER_GWEN                        1218
#define TRAINER_FRLG_BIKER_VIRGIL                          1219
#define TRAINER_FRLG_CAMPER_FLINT                          1220
#define TRAINER_FRLG_PICNICKER_MISSY                       1221
#define TRAINER_FRLG_PICNICKER_IRENE                       1222
#define TRAINER_FRLG_PICNICKER_DANA                        1223
#define TRAINER_FRLG_PICNICKER_ARIANA                      1224
#define TRAINER_FRLG_PICNICKER_LEAH                        1225
#define TRAINER_FRLG_CAMPER_JUSTIN                         1226
#define TRAINER_FRLG_PICNICKER_YAZMIN                      1227
#define TRAINER_FRLG_PICNICKER_KINDRA                      1228
#define TRAINER_FRLG_PICNICKER_BECKY                       1229
#define TRAINER_FRLG_PICNICKER_CELIA                       1230
#define TRAINER_FRLG_GENTLEMAN_BROOKS                      1231
#define TRAINER_FRLG_GENTLEMAN_LAMAR                       1232
#define TRAINER_FRLG_TWINS_ELI_ANNE                        1233
#define TRAINER_FRLG_COOL_COUPLE_RAY_TYRA                  1234
#define TRAINER_FRLG_YOUNG_COUPLE_GIA_JES                  1235
#define TRAINER_FRLG_TWINS_KIRI_JAN                        1236
#define TRAINER_FRLG_CRUSH_KIN_RON_MYA                     1237
#define TRAINER_FRLG_YOUNG_COUPLE_LEA_JED                  1238
#define TRAINER_FRLG_SIS_AND_BRO_LIA_LUC                   1239
#define TRAINER_FRLG_SIS_AND_BRO_LIL_IAN                   1240
#define TRAINER_FRLG_YOUNGSTER_BEN_3                       1241
#define TRAINER_FRLG_YOUNGSTER_BEN_4                       1242
#define TRAINER_FRLG_YOUNGSTER_CHAD_2                      1243
#define TRAINER_FRLG_LASS_RELI_2                           1244
#define TRAINER_FRLG_LASS_RELI_3                           1245
#define TRAINER_FRLG_YOUNGSTER_TIMMY_2                     1246
#define TRAINER_FRLG_YOUNGSTER_TIMMY_3                     1247
#define TRAINER_FRLG_YOUNGSTER_TIMMY_4                     1248
#define TRAINER_FRLG_YOUNGSTER_CHAD_3                      1249
#define TRAINER_FRLG_LASS_JANICE_2                         1250
#define TRAINER_FRLG_LASS_JANICE_3                         1251
#define TRAINER_FRLG_YOUNGSTER_CHAD_4                      1252
#define TRAINER_FRLG_HIKER_FRANKLIN_2                      1253
#define TRAINER_FRLG_PKMN_PROF_PROF_OAK                    1254
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_42                  1255
#define TRAINER_FRLG_PSYCHIC_JACLYN                        1256
#define TRAINER_FRLG_CRUSH_GIRL_SHARON                     1257
#define TRAINER_FRLG_TUBER_AMIRA                           1258
#define TRAINER_FRLG_PKMN_BREEDER_ALIZE                    1259
#define TRAINER_FRLG_PKMN_RANGER_NICOLAS                   1260
#define TRAINER_FRLG_PKMN_RANGER_MADELINE                  1261
#define TRAINER_FRLG_AROMA_LADY_NIKKI                      1262
#define TRAINER_FRLG_RUIN_MANIAC_STANLY                    1263
#define TRAINER_FRLG_LADY_JACKI                            1264
#define TRAINER_FRLG_PAINTER_DAISY                         1265
#define TRAINER_FRLG_BIKER_GOON                            1266
#define TRAINER_FRLG_BIKER_GOON_2                          1267
#define TRAINER_FRLG_BIKER_GOON_3                          1268
#define TRAINER_FRLG_BUG_CATCHER_ANTHONY                   1269
#define TRAINER_FRLG_BUG_CATCHER_CHARLIE                   1270
#define TRAINER_FRLG_TWINS_ELI_ANNE_2                      1271
#define TRAINER_FRLG_YOUNGSTER_JOHNSON                     1272
#define TRAINER_FRLG_BIKER_RICARDO                         1273
#define TRAINER_FRLG_BIKER_JAREN                           1274
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_43                  1275
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_44                  1276
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_45                  1277
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_46                  1278
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_47                  1279
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_48                  1280
#define TRAINER_FRLG_TEAM_ROCKET_ADMIN                     1281
#define TRAINER_FRLG_TEAM_ROCKET_ADMIN_2                   1282
#define TRAINER_FRLG_SCIENTIST_GIDEON                      1283
#define TRAINER_FRLG_SWIMMER_FEMALE_AMARA                  1284
#define TRAINER_FRLG_SWIMMER_FEMALE_MARIA                  1285
#define TRAINER_FRLG_SWIMMER_FEMALE_ABIGAIL                1286
#define TRAINER_FRLG_SWIMMER_MALE_FINN                     1287
#define TRAINER_FRLG_SWIMMER_MALE_GARRETT                  1288
#define TRAINER_FRLG_FISHERMAN_TOMMY                       1289
#define TRAINER_FRLG_CRUSH_GIRL_TANYA                      1290
#define TRAINER_FRLG_BLACK_BELT_SHEA                       1291
#define TRAINER_FRLG_BLACK_BELT_HUGH                       1292
#define TRAINER_FRLG_CAMPER_BRYCE                          1293
#define TRAINER_FRLG_PICNICKER_CLAIRE                      1294
#define TRAINER_FRLG_CRUSH_KIN_MIK_KIA                     1295
#define TRAINER_FRLG_AROMA_LADY_VIOLET                     1296
#define TRAINER_FRLG_TUBER_ALEXIS                          1297
#define TRAINER_FRLG_TWINS_JOY_MEG                         1298
#define TRAINER_FRLG_SWIMMER_FEMALE_TISHA                  1299
#define TRAINER_FRLG_PAINTER_CELINA                        1300
#define TRAINER_FRLG_PAINTER_RAYNA                         1301
#define TRAINER_FRLG_LADY_GILLIAN                          1302
#define TRAINER_FRLG_YOUNGSTER_DESTIN                      1303
#define TRAINER_FRLG_SWIMMER_MALE_TOBY                     1304
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_49                  1305
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_50                  1306
#define TRAINER_FRLG_TEAM_ROCKET_GRUNT_51                  1307
#define TRAINER_FRLG_BIRD_KEEPER_MILO                      1308
#define TRAINER_FRLG_BIRD_KEEPER_CHAZ                      1309
#define TRAINER_FRLG_BIRD_KEEPER_HAROLD                    1310
#define TRAINER_FRLG_FISHERMAN_TYLOR                       1311
#define TRAINER_FRLG_SWIMMER_MALE_MYMO                     1312
#define TRAINER_FRLG_SWIMMER_FEMALE_NICOLE                 1313
#define TRAINER_FRLG_SIS_AND_BRO_AVA_GEB                   1314
#define TRAINER_FRLG_AROMA_LADY_ROSE                       1315
#define TRAINER_FRLG_SWIMMER_MALE_SAMIR                    1316
#define TRAINER_FRLG_SWIMMER_FEMALE_DENISE                 1317
#define TRAINER_FRLG_TWINS_MIU_MIA                         1318
#define TRAINER_FRLG_HIKER_EARL                            1319
#define TRAINER_FRLG_RUIN_MANIAC_FOSTER                    1320
#define TRAINER_FRLG_RUIN_MANIAC_LARRY                     1321
#define TRAINER_FRLG_HIKER_DARYL                           1322
#define TRAINER_FRLG_POKEMANIAC_HECTOR                     1323
#define TRAINER_FRLG_PSYCHIC_DARIO                         1324
#define TRAINER_FRLG_PSYCHIC_RODETTE                       1325
#define TRAINER_FRLG_AROMA_LADY_MIAH                       1326
#define TRAINER_FRLG_YOUNG_COUPLE_EVE_JON                  1327
#define TRAINER_FRLG_JUGGLER_MASON                         1328
#define TRAINER_FRLG_CRUSH_GIRL_CYNDY                      1329
#define TRAINER_FRLG_CRUSH_GIRL_JOCELYN                    1330
#define TRAINER_FRLG_TAMER_EVAN                            1331
#define TRAINER_FRLG_POKEMANIAC_MARK_2                     1332
#define TRAINER_FRLG_PKMN_RANGER_LOGAN                     1333
#define TRAINER_FRLG_PKMN_RANGER_JACKSON                   1334
#define TRAINER_FRLG_PKMN_RANGER_BETH                      1335
#define TRAINER_FRLG_PKMN_RANGER_KATELYN                   1336
#define TRAINER_FRLG_COOLTRAINER_LEROY                     1337
#define TRAINER_FRLG_COOLTRAINER_MICHELLE                  1338
#define TRAINER_FRLG_COOL_COUPLE_LEX_NYA                   1339
#define TRAINER_FRLG_RUIN_MANIAC_BRANDON                   1340
#define TRAINER_FRLG_RUIN_MANIAC_BENJAMIN                  1341
#define TRAINER_FRLG_PAINTER_EDNA                          1342
#define TRAINER_FRLG_GENTLEMAN_CLIFFORD                    1343
#define TRAINER_FRLG_LADY_SELPHY                           1344
#define TRAINER_FRLG_RUIN_MANIAC_LAWSON                    1345
#define TRAINER_FRLG_PSYCHIC_LAURA                         1346
#define TRAINER_FRLG_PKMN_BREEDER_BETHANY                  1347
#define TRAINER_FRLG_PKMN_BREEDER_ALLISON                  1348
#define TRAINER_FRLG_BUG_CATCHER_GARRET                    1349
#define TRAINER_FRLG_BUG_CATCHER_JONAH                     1350
#define TRAINER_FRLG_BUG_CATCHER_VANCE                     1351
#define TRAINER_FRLG_YOUNGSTER_NASH                        1352
#define TRAINER_FRLG_YOUNGSTER_CORDELL                     1353
#define TRAINER_FRLG_LASS_DALIA                            1354
#define TRAINER_FRLG_LASS_JOANA                            1355
#define TRAINER_FRLG_CAMPER_RILEY                          1356
#define TRAINER_FRLG_PICNICKER_MARCY                       1357
#define TRAINER_FRLG_RUIN_MANIAC_LAYTON                    1358
#define TRAINER_FRLG_PICNICKER_KELSEY_2                    1359
#define TRAINER_FRLG_PICNICKER_KELSEY_3                    1360
#define TRAINER_FRLG_PICNICKER_KELSEY_4                    1361
#define TRAINER_FRLG_CAMPER_RICKY_2                        1362
#define TRAINER_FRLG_CAMPER_RICKY_3                        1363
#define TRAINER_FRLG_CAMPER_RICKY_4                        1364
#define TRAINER_FRLG_CAMPER_JEFF_2                         1365
#define TRAINER_FRLG_CAMPER_JEFF_3                         1366
#define TRAINER_FRLG_CAMPER_JEFF_4                         1367
#define TRAINER_FRLG_PICNICKER_ISABELLE_2                  1368
#define TRAINER_FRLG_PICNICKER_ISABELLE_3                  1369
#define TRAINER_FRLG_PICNICKER_ISABELLE_4                  1370
#define TRAINER_FRLG_YOUNGSTER_YASU_2                      1371
#define TRAINER_FRLG_YOUNGSTER_YASU_3                      1372
#define TRAINER_FRLG_ENGINEER_BERNIE_2                     1373
#define TRAINER_FRLG_GAMER_DARIAN_2                        1374
#define TRAINER_FRLG_CAMPER_CHRIS_2                        1375
#define TRAINER_FRLG_CAMPER_CHRIS_3                        1376
#define TRAINER_FRLG_CAMPER_CHRIS_4                        1377
#define TRAINER_FRLG_PICNICKER_ALICIA_2                    1378
#define TRAINER_FRLG_PICNICKER_ALICIA_3                    1379
#define TRAINER_FRLG_PICNICKER_ALICIA_4                    1380
#define TRAINER_FRLG_HIKER_JEREMY_2                        1381
#define TRAINER_FRLG_POKEMANIAC_MARK_3                     1382
#define TRAINER_FRLG_POKEMANIAC_HERMAN_2                   1383
#define TRAINER_FRLG_POKEMANIAC_HERMAN_3                   1384
#define TRAINER_FRLG_HIKER_TRENT_2                         1385
#define TRAINER_FRLG_LASS_MEGAN_2                          1386
#define TRAINER_FRLG_LASS_MEGAN_3                          1387
#define TRAINER_FRLG_SUPER_NERD_GLENN_2                    1388
#define TRAINER_FRLG_GAMER_RICH_2                          1389
#define TRAINER_FRLG_BIKER_JAREN_2                         1390
#define TRAINER_FRLG_FISHERMAN_ELLIOT_2                    1391
#define TRAINER_FRLG_ROCKER_LUCA_2                         1392
#define TRAINER_FRLG_BEAUTY_SHEILA_2                       1393
#define TRAINER_FRLG_BIRD_KEEPER_ROBERT_2                  1394
#define TRAINER_FRLG_BIRD_KEEPER_ROBERT_3                  1395
#define TRAINER_FRLG_PICNICKER_SUSIE_2                     1396
#define TRAINER_FRLG_PICNICKER_SUSIE_3                     1397
#define TRAINER_FRLG_PICNICKER_SUSIE_4                     1398
#define TRAINER_FRLG_BIKER_LUKAS_2                         1399
#define TRAINER_FRLG_BIRD_KEEPER_BENNY_2                   1400
#define TRAINER_FRLG_BIRD_KEEPER_BENNY_3                   1401
#define TRAINER_FRLG_BIRD_KEEPER_MARLON_2                  1402
#define TRAINER_FRLG_BIRD_KEEPER_MARLON_3                  1403
#define TRAINER_FRLG_BEAUTY_GRACE_2                        1404
#define TRAINER_FRLG_BIRD_KEEPER_CHESTER_2                 1405
#define TRAINER_FRLG_BIRD_KEEPER_CHESTER_3                 1406
#define TRAINER_FRLG_PICNICKER_BECKY_2                     1407
#define TRAINER_FRLG_PICNICKER_BECKY_3                     1408
#define TRAINER_FRLG_PICNICKER_BECKY_4                     1409
#define TRAINER_FRLG_CRUSH_KIN_RON_MYA_2                   1410
#define TRAINER_FRLG_CRUSH_KIN_RON_MYA_3                   1411
#define TRAINER_FRLG_CRUSH_KIN_RON_MYA_4                   1412
#define TRAINER_FRLG_BIKER_RUBEN_2                         1413
#define TRAINER_FRLG_CUE_BALL_CAMRON_2                     1414
#define TRAINER_FRLG_BIKER_JAXON_2                         1415
#define TRAINER_FRLG_CUE_BALL_ISAIAH_2                     1416
#define TRAINER_FRLG_CUE_BALL_COREY_2                      1417
#define TRAINER_FRLG_BIRD_KEEPER_JACOB_2                   1418
#define TRAINER_FRLG_BIRD_KEEPER_JACOB_3                   1419
#define TRAINER_FRLG_SWIMMER_FEMALE_ALICE_2                1420
#define TRAINER_FRLG_SWIMMER_MALE_DARRIN_2                 1421
#define TRAINER_FRLG_PICNICKER_MISSY_2                     1422
#define TRAINER_FRLG_PICNICKER_MISSY_3                     1423
#define TRAINER_FRLG_FISHERMAN_WADE_2                      1424
#define TRAINER_FRLG_SWIMMER_MALE_JACK_2                   1425
#define TRAINER_FRLG_SIS_AND_BRO_LIL_IAN_2                 1426
#define TRAINER_FRLG_SIS_AND_BRO_LIL_IAN_3                 1427
#define TRAINER_FRLG_SWIMMER_MALE_FINN_2                   1428
#define TRAINER_FRLG_CRUSH_GIRL_SHARON_2                   1429
#define TRAINER_FRLG_CRUSH_GIRL_SHARON_3                   1430
#define TRAINER_FRLG_CRUSH_GIRL_TANYA_2                    1431
#define TRAINER_FRLG_CRUSH_GIRL_TANYA_3                    1432
#define TRAINER_FRLG_BLACK_BELT_SHEA_2                     1433
#define TRAINER_FRLG_BLACK_BELT_SHEA_3                     1434
#define TRAINER_FRLG_BLACK_BELT_HUGH_2                     1435
#define TRAINER_FRLG_BLACK_BELT_HUGH_3                     1436
#define TRAINER_FRLG_CRUSH_KIN_MIK_KIA_2                   1437
#define TRAINER_FRLG_CRUSH_KIN_MIK_KIA_3                   1438
#define TRAINER_FRLG_TUBER_AMIRA_2                         1439
#define TRAINER_FRLG_TWINS_JOY_MEG_2                       1440
#define TRAINER_FRLG_PAINTER_RAYNA_2                       1441
#define TRAINER_FRLG_YOUNGSTER_DESTIN_2                    1442
#define TRAINER_FRLG_PKMN_BREEDER_ALIZE_2                  1443
#define TRAINER_FRLG_YOUNG_COUPLE_GIA_JES_2                1444
#define TRAINER_FRLG_YOUNG_COUPLE_GIA_JES_3                1445
#define TRAINER_FRLG_BIRD_KEEPER_MILO_2                    1446
#define TRAINER_FRLG_BIRD_KEEPER_CHAZ_2                    1447
#define TRAINER_FRLG_BIRD_KEEPER_HAROLD_2                  1448
#define TRAINER_FRLG_SWIMMER_FEMALE_NICOLE_2               1449
#define TRAINER_FRLG_PSYCHIC_JACLYN_2                      1450
#define TRAINER_FRLG_SWIMMER_MALE_SAMIR_2                  1451
#define TRAINER_FRLG_HIKER_EARL_2                          1452
#define TRAINER_FRLG_RUIN_MANIAC_LARRY_2                   1453
#define TRAINER_FRLG_POKEMANIAC_HECTOR_2                   1454
#define TRAINER_FRLG_PSYCHIC_DARIO_2                       1455
#define TRAINER_FRLG_PSYCHIC_RODETTE_2                     1456
#define TRAINER_FRLG_JUGGLER_MASON_2                       1457
#define TRAINER_FRLG_PKMN_RANGER_NICOLAS_2                 1458
#define TRAINER_FRLG_PKMN_RANGER_MADELINE_2                1459
#define TRAINER_FRLG_CRUSH_GIRL_CYNDY_2                    1460
#define TRAINER_FRLG_TAMER_EVAN_2                          1461
#define TRAINER_FRLG_PKMN_RANGER_JACKSON_2                 1462
#define TRAINER_FRLG_PKMN_RANGER_KATELYN_2                 1463
#define TRAINER_FRLG_COOLTRAINER_LEROY_2                   1464
#define TRAINER_FRLG_COOLTRAINER_MICHELLE_2                1465
#define TRAINER_FRLG_COOL_COUPLE_LEX_NYA_2                 1466
#define TRAINER_FRLG_BUG_CATCHER_COLTON_2                  1467
#define TRAINER_FRLG_BUG_CATCHER_COLTON_3                  1468
#define TRAINER_FRLG_BUG_CATCHER_COLTON_4                  1469
#define TRAINER_FRLG_SWIMMER_MALE_MATTHEW_2                1470
#define TRAINER_FRLG_SWIMMER_MALE_TONY_2                   1471
#define TRAINER_FRLG_SWIMMER_FEMALE_MELISSA_2              1472
#define TRAINER_FRLG_ELITE_FOUR_LORELEI_2                  1473
#define TRAINER_FRLG_ELITE_FOUR_BRUNO_2                    1474
#define TRAINER_FRLG_ELITE_FOUR_AGATHA_2                   1475
#define TRAINER_FRLG_ELITE_FOUR_LANCE_2                    1476
#define TRAINER_FRLG_CHAMPION_REMATCH_SQUIRTLE             1477
#define TRAINER_FRLG_CHAMPION_REMATCH_BULBASAUR            1478
#define TRAINER_FRLG_CHAMPION_REMATCH_CHARMANDER           1479
#define TRAINER_FRLG_CUE_BALL_PAXTON                       1480

// Legacy product bounds retained with the collision tombstones; neither is a runtime bound.
#define TRAINERS_COUNT_FRLG                      624
#define MAX_TRAINERS_COUNT_FRLG                  768

#endif  // GUARD_CONSTANTS_OPPONENTS_FRLG_H
