#ifndef GUARD_CONSTANTS_SAFARI_ZONE_H
#define GUARD_CONSTANTS_SAFARI_ZONE_H

#define SAFARI_ZONE_FACILITY_NONE            0
#define SAFARI_ZONE_FACILITY_HOENN_ROUTE_121 1
#define SAFARI_ZONE_FACILITY_KANTO_FUCHSIA   2

#define SAFARI_ZONE_HOENN_STEP_LIMIT 500
#define SAFARI_ZONE_KANTO_STEP_LIMIT 600

#endif // GUARD_CONSTANTS_SAFARI_ZONE_H
