Common_EventScript_RegionalCableClubUnavailable::
	lock
	faceplayer
	msgbox Common_Text_RegionalCableClubUnavailable
	release
	end

Common_EventScript_DeferredVersionTrade::
	lock
	faceplayer
	msgbox Common_Text_DeferredVersionTrade
	release
	end

Common_Text_RegionalCableClubUnavailable::
	.string "These communication services aren't\n"
	.string "available in this region right now.$"

Common_Text_DeferredVersionTrade::
	.string "I'm not ready to trade right now.\n"
	.string "Please come back later.$"
