#ifndef GUARD_PLAYER_CAPABILITY_H
#define GUARD_PLAYER_CAPABILITY_H

#include "global.h"

enum PlayerCapability
{
    PLAYER_CAPABILITY_CUT,
    PLAYER_CAPABILITY_FLASH,
    PLAYER_CAPABILITY_ROCK_SMASH,
    PLAYER_CAPABILITY_STRENGTH,
    PLAYER_CAPABILITY_SURF,
    PLAYER_CAPABILITY_FLY,
    PLAYER_CAPABILITY_DIVE,
    PLAYER_CAPABILITY_WATERFALL,
    PLAYER_CAPABILITY_COUNT,
};

bool32 PlayerHasCapability(enum PlayerCapability capability);

#endif // GUARD_PLAYER_CAPABILITY_H
