#ifndef GUARD_REGIONAL_FACT_H
#define GUARD_REGIONAL_FACT_H

#include "global.h"

enum RegionalFact
{
    REGIONAL_FACT_HOENN_STONE_BADGE,
    REGIONAL_FACT_KANTO_CASCADE_BADGE,
    REGIONAL_FACT_JOHTO_HIVE_BADGE,
    REGIONAL_FACT_HOENN_KNUCKLE_BADGE,
    REGIONAL_FACT_KANTO_BOULDER_BADGE,
    REGIONAL_FACT_JOHTO_ZEPHYR_BADGE,
    REGIONAL_FACT_HOENN_DYNAMO_BADGE,
    REGIONAL_FACT_KANTO_MARSH_BADGE,
    REGIONAL_FACT_HOENN_HEAT_BADGE,
    REGIONAL_FACT_KANTO_RAINBOW_BADGE,
    REGIONAL_FACT_JOHTO_PLAIN_BADGE,
    REGIONAL_FACT_HOENN_BALANCE_BADGE,
    REGIONAL_FACT_KANTO_SOUL_BADGE,
    REGIONAL_FACT_JOHTO_FOG_BADGE,
    REGIONAL_FACT_HOENN_FEATHER_BADGE,
    REGIONAL_FACT_KANTO_THUNDER_BADGE,
    REGIONAL_FACT_JOHTO_STORM_BADGE,
    REGIONAL_FACT_HOENN_MIND_BADGE,
    REGIONAL_FACT_HOENN_RAIN_BADGE,
    REGIONAL_FACT_KANTO_VOLCANO_BADGE,
    REGIONAL_FACT_JOHTO_RISING_BADGE,
    REGIONAL_FACT_KANTO_SS_ANNE_CUT_RECEIVED,
    REGIONAL_FACT_KANTO_MR_FUJI_RESCUED,
    REGIONAL_FACT_KANTO_SILPH_SAVED,
    REGIONAL_FACT_KANTO_CHAMPION_CROWNED,
    REGIONAL_FACT_HOENN_DEVON_GOODS_DELIVERED,
    REGIONAL_FACT_HOENN_SURF_RECEIVED,
    REGIONAL_FACT_HOENN_DEVON_SCOPE_RECEIVED,
    REGIONAL_FACT_HOENN_SPACE_CENTER_SAVED,
    REGIONAL_FACT_HOENN_DIVE_RECEIVED,
    REGIONAL_FACT_HOENN_WALLY_VICTORY_ROAD_DEFEATED,
    REGIONAL_FACT_HOENN_WATERFALL_RECEIVED,
    REGIONAL_FACT_SEVII_LOSTELLE_RESCUED,
    REGIONAL_FACT_SEVII_RUBY_RECOVERED,
    REGIONAL_FACT_SEVII_SAPPHIRE_RECOVERED,
    REGIONAL_FACT_SEVII_DETOUR_FINISHED,
    REGIONAL_FACT_COUNT,
};

bool32 RegionalFact_Get(enum RegionalFact fact);

#endif // GUARD_REGIONAL_FACT_H
