#ifndef GUARD_REGIONAL_FACT_H
#define GUARD_REGIONAL_FACT_H

#include "global.h"

enum RegionalFact
{
    REGIONAL_FACT_HOENN_STONE_BADGE,
    REGIONAL_FACT_KANTO_CASCADE_BADGE,
    REGIONAL_FACT_JOHTO_HIVE_BADGE,
    REGIONAL_FACT_HOENN_KNUCKLE_BADGE,
    REGIONAL_FACT_KANTO_BOULDER_BADGE,
    REGIONAL_FACT_JOHTO_ZEPHYR_BADGE,
    REGIONAL_FACT_HOENN_DYNAMO_BADGE,
    REGIONAL_FACT_KANTO_MARSH_BADGE,
    REGIONAL_FACT_HOENN_HEAT_BADGE,
    REGIONAL_FACT_KANTO_RAINBOW_BADGE,
    REGIONAL_FACT_JOHTO_PLAIN_BADGE,
    REGIONAL_FACT_HOENN_BALANCE_BADGE,
    REGIONAL_FACT_KANTO_SOUL_BADGE,
    REGIONAL_FACT_JOHTO_FOG_BADGE,
    REGIONAL_FACT_HOENN_FEATHER_BADGE,
    REGIONAL_FACT_KANTO_THUNDER_BADGE,
    REGIONAL_FACT_JOHTO_STORM_BADGE,
    REGIONAL_FACT_HOENN_MIND_BADGE,
    REGIONAL_FACT_HOENN_RAIN_BADGE,
    REGIONAL_FACT_KANTO_VOLCANO_BADGE,
    REGIONAL_FACT_JOHTO_RISING_BADGE,
    REGIONAL_FACT_SEVII_DETOUR_FINISHED,
    REGIONAL_FACT_COUNT,
};

bool32 RegionalFact_Get(enum RegionalFact fact);

#endif // GUARD_REGIONAL_FACT_H
