#include "global.h"
#include "event_data.h"
#include "regional_fact.h"

bool32 RegionalFact_Get(enum RegionalFact fact)
{
    switch (fact)
    {
    case REGIONAL_FACT_HOENN_STONE_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_STONE_BADGE);
    case REGIONAL_FACT_KANTO_CASCADE_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_CASCADE_BADGE);
    case REGIONAL_FACT_JOHTO_HIVE_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_HIVE_BADGE);
    case REGIONAL_FACT_HOENN_KNUCKLE_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_KNUCKLE_BADGE);
    case REGIONAL_FACT_KANTO_BOULDER_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_BOULDER_BADGE);
    case REGIONAL_FACT_JOHTO_ZEPHYR_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_ZEPHYR_BADGE);
    case REGIONAL_FACT_HOENN_DYNAMO_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_DYNAMO_BADGE);
    case REGIONAL_FACT_KANTO_MARSH_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_MARSH_BADGE);
    case REGIONAL_FACT_HOENN_HEAT_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_HEAT_BADGE);
    case REGIONAL_FACT_KANTO_RAINBOW_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_RAINBOW_BADGE);
    case REGIONAL_FACT_JOHTO_PLAIN_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_PLAIN_BADGE);
    case REGIONAL_FACT_HOENN_BALANCE_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_BALANCE_BADGE);
    case REGIONAL_FACT_KANTO_SOUL_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_SOUL_BADGE);
    case REGIONAL_FACT_JOHTO_FOG_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_FOG_BADGE);
    case REGIONAL_FACT_HOENN_FEATHER_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_FEATHER_BADGE);
    case REGIONAL_FACT_KANTO_THUNDER_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_THUNDER_BADGE);
    case REGIONAL_FACT_JOHTO_STORM_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_STORM_BADGE);
    case REGIONAL_FACT_HOENN_MIND_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_MIND_BADGE);
    case REGIONAL_FACT_HOENN_RAIN_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_HOENN_RAIN_BADGE);
    case REGIONAL_FACT_KANTO_VOLCANO_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_KANTO_VOLCANO_BADGE);
    case REGIONAL_FACT_JOHTO_RISING_BADGE:
        return FlagGet(FLAG_REGIONAL_FACT_JOHTO_RISING_BADGE);
    case REGIONAL_FACT_SEVII_DETOUR_FINISHED:
        return FlagGet(FLAG_REGIONAL_FACT_SEVII_DETOUR_FINISHED);
    default:
        return FALSE;
    }
}
